### ISSUE TITLE
transferUsersPlayback does not contain Body

### ISSUE THREAD

**Issue by Bart1909** [thelinmichael/spotify-web-api-java#129]
When calling the Method 
api.transferUsersPlayback(deviceIds).play(false).build().execute();
I got the Spotify error message that the required field device_ids is not set.

The implementation for AbstractRequest.putJson() does not set the bodyparameters, only the form parameters which are empty.

**Comment by Dargmuesli** [comment]
Could be closely connected to #126 which was fixed this morning. I'm going to release another RC soon.

**Comment by Dargmuesli** [comment]
Please try version 2.0.0-RC2 and test if the issue still occurs. RC2 was just released and will be accessible within the next hours.

**Comment by Bart1909** [comment]
Hi @Dargmuesli,

it is still not working. I debugged the code and saw, that now, the HttpEntity body is submitted in the put-Request instead of the List<NameValuePair> bodyParameters.

**Comment by Dargmuesli** [comment]
I've tested and fixed the issue. Thanks for reporting!
Please use [Jitpack](https://jitpack.io/) to test the current master branch as RC3's release will still take some time.
