### ISSUE TITLE
Get Playlist Tracks

### ISSUE THREAD

**Issue by QuerGamer** [thelinmichael/spotify-web-api-java#236]
I have not found an example at: [GetPlaylistsTracksExample.java](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/playlists/GetPlaylistsTracksExample.java.)
Unfortunately, this page does not exist.

**Java:**
```  Java 
Paging<PlaylistSimplified> playlist = spotifyApi.searchPlaylists(tag).build().execute();
```

How do I get from the playlist to the tracks in the playlist?

**Comment by dargmuesli** [comment]
Thanks for the hint! The links have been fixed. You can find the example at [GetPlaylistsItemsExample.java](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/playlists/GetPlaylistsItemsExample.java).

**Comment by QuerGamer** [comment]
Thanks for the quick answer

**Comment by QuerGamer** [comment]
i still don't quite understand how to get to the tracks after the request 
```Java
Paging<PlaylistSimplified> playlist = spotifyApi.searchPlaylists(tag).build().execute();
```
i do not have the playlist id after the search.

**Comment by dargmuesli** [comment]
See https://github.com/thelinmichael/spotify-web-api-java/blob/master/CONTRIBUTING.md#your-questions.
Please post questions on Stackoverflow using the label `spotify-web-api-java`.

You might be interested in the [Paging class](http://michaelthelin.se/spotify-web-api-java/com/wrapper/spotify/model_objects/specification/Paging.html) on your way to the solution. It has a `getItems` method.

**Comment by reol224** [comment]
```
var response = spotifyConnect.getSpotifyApi().searchPlaylists(id).build().execute();

        List<PlaylistModel> list = new ArrayList<>();
        for(PlaylistSimplified playlist : response.getItems()){
            String href = playlist.getHref();
            ExternalUrl externalUrls = playlist.getExternalUrls();
            String playlistName = playlist.getName();
            PlaylistTracksInformation tracks = playlist.getTracks();
            Image[] playlistCover = playlist.getImages();

            list.add(new PlaylistModel(href, externalUrls, playlistName, tracks, playlistCover));
        }

        Map<String, Object> map = new HashMap<>();
        map.put("Playlist", list);
        return map;
```

this is one way of doing it
to mention that you should always check with response dot,so if it has getItems,u can iterate through it
